name: Bug Report
description: Report something that isn't working correctly
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: A clear description of the bug.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Go to...
        2. Tap...
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: MyDeck version
      placeholder: e.g. 0.9.2
    validations:
      required: true

  - type: input
    id: android
    attributes:
      label: Android version and device
      placeholder: e.g. Android 14, Pixel 7
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs or debug info (optional)
      description: >
        Logs can be exported from **Settings → Logs** using the share icon.
        Debug info for a specific bookmark is available in the Bookmark Details
        screen on debug builds.
      render: text
